repos:
  # Quick content checks based on grepping for python specific patterns:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks # Find single rather than double backticks
      - id: rst-directive-colons # Missing double-colons after directives
      - id: rst-inline-touching-normal # Inline code should never touch normal text
      - id: python-use-type-annotations # Use annotations not old-style type comments

  # Other file formatting, plus common Git mistakes & text file standardization:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # Don't accidentally commit giant files.
      - id: check-merge-conflict # Watch for lingering merge markers.
      - id: check-yaml # Validate all YAML files.
      - id: check-toml
      - id: check-case-conflict # Avoid case sensitivity in file names.
      - id: debug-statements # Watch for lingering debugger calls.
      - id: mixed-line-ending # Use Unix line-endings to avoid big no-op CSV diffs.
        args: ["--fix=lf"]
      - id: trailing-whitespace
  #      - id: name-tests-test # Follow PyTest naming convention.
  #      - id: end-of-file-fixer

  ####################################################################################
  # Formatters: hooks that re-write Python & documentation files
  ####################################################################################
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v3.1.0
#    hooks:
#      - id: prettier
#        types_or: [yaml]
