name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=127

    - name: Fixing linting errors
      run: |
        black .

    - name: Environment Variables
      env:
        MONGODB_DATABASE: ''
        MONGODB_URL: ''
        APIKEY: ''
      #        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
#        MONGODB_URL: ${{ secrets.MONGODB_URL }}
#        APIKEY: ${{ secrets.APIKEY }}

    - name: Test with pytest
      run: |
        pytest