name: CI
on: [push, pull_request]
jobs:
  build:
    env:
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      APIKEY: ${{ secrets.APIKEY }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit hooks
        run: |
          pre-commit clean
          pre-commit run --all-files
